// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_webm_ from "./routes/[webm].tsx";
import * as $_app from "./routes/_app.tsx";
import * as $id from "./routes/id.tsx";
import * as $random from "./routes/random.tsx";
import * as $viewer from "./routes/viewer.tsx";
import * as $viewer_1 from "./islands/viewer.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[webm].tsx": $_webm_,
    "./routes/_app.tsx": $_app,
    "./routes/id.tsx": $id,
    "./routes/random.tsx": $random,
    "./routes/viewer.tsx": $viewer,
  },
  islands: {
    "./islands/viewer.tsx": $viewer_1,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
